### ISSUE TITLE
Column Spacer Option

### ISSUE THREAD

**Issue by MikeFez** [benct/lovelace-multiple-entity-row#106]
Hello! 

I have a vertical column populated with this card set up for monitoring the climate of various rooms. The layout is typically Room Name [Dehumidifier Switch, AC Switch, Temperature, Humidity]. Visually this is excellent as everything is laid out in in the same column, making it easy to quickly parse the information needed at a glance. That being said, some rooms may be missing values - such as, not every room has a dehumidifier/AC, and not every room has humidity readings. And so what typically happens is that a few columns have their "type" shifted right one column.

It would be nice to be able to add a spacer so that even if an item is missing, the row/column structure remains the same.

**Comment by benct** [comment]
The problem is that the entities are rendered dynamically for each row, so there's no way for a "spacer" to know the correct width to match up with other rows. You would have to specify a fixed with for the spacer I guess, which is not optimal..

Could you maybe try to achieve the desired spacings with [card-mod](https://github.com/thomasloven/lovelace-card-mod) instead?

**Comment by MikeFez** [comment]
Hi Ben!

Thanks for the reply - after taking a second look at my UI, I can indeed see that the spacing of the "columns" are not a fixed percentage and instead are based upon the content of the entity being displayed.

I'll try out card mod for this - thanks again!
