### ISSUE TITLE
Support for timer

### ISSUE THREAD

**Issue by circa1665** [benct/lovelace-multiple-entity-row#12]
3 things 😬:

1. It would be great if we could show info, primary or secondary based on conditional states.

2. Also cool if [timers](https://www.home-assistant.io/components/timer/) could show remaining time rather than "active".

3. Would like to have control over the display format: e.g. 00:02:30, 02:30, 2 min 30 sec, 150 sec

<img width="441" alt="timer" src="https://user-images.githubusercontent.com/33236082/65840872-d17d9f00-e315-11e9-9909-4e94ea39942f.png">

E.g. in this example switch activates a 2 min timer, when it reaches 0 an automation turns off the switch. Would like to be able to hide the timer when inactive, currently shows as "idle". Realise this might be bit niche 😕

**Comment by benct** [comment]
I have the some kind of timer in my HA setup and agree that it would be much better to have it display the time rather than "active" :) I'll try to implement that as soon as I have the time (possibly with formatting options, will have to check how easy that is to handle in the cards).

I'll add conditional states to my list of things to add in the future!

**Comment by circa1665** [comment]
That's great, thank you! I look out for it 👍

**Comment by benct** [comment]
I just looked through the states and attributes of my timer on HA and quickly found a "small" problem. There is no (updated) value available for the remaining time... There is an attribute on the timer called `remaining`, but this does not update as the timer progresses.

After googling a bit and reading the HA forums, this seems to be by design as it would be too processor intensive to update all timers every second (or even more often). So I'm afraid I am not able to implement this as initially hoped :(
