### ISSUE TITLE
Spacing issue between row name and sub entities

### ISSUE THREAD

**Issue by SAOPP** [benct/lovelace-multiple-entity-row#176]
Is it possible to automatically shift entities to the left closer to the main name if there are more than 3 of them?

For-example, I got it ova here:

![image](https://user-images.githubusercontent.com/5647009/109795201-52ce1500-7c1f-11eb-8098-3f726f050d4c.png)

If I add anotha sub-entity, in this example this is the lights, this card would be looks like this:

![image](https://user-images.githubusercontent.com/5647009/109795136-42b63580-7c1f-11eb-8254-dd9c959573a6.png)

It can be fixed? Thanks.

**Comment by SAOPP** [comment]
And one more example, on the left there is a place to place the rssi sensor in one line, instead, as u can see in the screenshot, it is located on two lines, I would like such things to move closer to the left edge:

![image](https://user-images.githubusercontent.com/5647009/109795509-afc9cb00-7c1f-11eb-842b-a47450d949a3.png)

**Comment by bpetrikovics** [comment]
I second this. Maybe a padding option to allow us to reduce the unused area. I've noticed that rows with more than 3 entities are cut from the right unless my browser is running fullscreen, and also leaving off the right-most entities when I'm watching via mobile on the companion app (e.g. as if there were no further entities - no indication that information was cut).

**Comment by SAOPP** [comment]
Also anotha the same examples:

![image](https://user-images.githubusercontent.com/5647009/110489158-d55f4480-80f7-11eb-8901-38140587f166.png)

![image](https://user-images.githubusercontent.com/5647009/110489262-ed36c880-80f7-11eb-844a-5b8e0806d924.png)

And mobile app issue:

![image](https://user-images.githubusercontent.com/5647009/110490115-ab5a5200-80f8-11eb-89da-6aecd9174e41.png)

**Comment by denilsonsa** [comment]
One more example…

I wanted to have four toggles in a single row (related to [Adaptive Lighting component](https://github.com/basnijholt/adaptive-lighting)). [lovelace-multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row) can do that, but the toggles get cropped to the right, so not all of them are visible. I also tried [lovelace-paper-buttons-row](https://github.com/jcwillox/lovelace-paper-buttons-row), which manages to make all the buttons visible, but they are now ugly buttons instead of nice toggles.

![Screenshot 1](https://user-images.githubusercontent.com/121676/112082720-1fc7d300-8b86-11eb-875a-0e98b5723345.png)

Being able to remove the main name (and optionally also the icon) would be awesome for this case. Look:

![Screenshot 2](https://user-images.githubusercontent.com/121676/112083355-2571e880-8b87-11eb-8853-6ba9b128029a.png)

That screenshot was made after adding `display: none` to the `.info` element inside `<hui-generic-entity-row>`, and then adding `margin: auto` to `.entities-row` to make the buttons centered (alternatively I could have used `justify-content: space-between` on the `<hui-generic-entity-row>` element, as that would keep the icon left-aligned while the buttons go right-aligned). I've done that on the browser developer tools, I don't have any code to share.

I can understand `multiple-entity-row` is reusing Home Assistant's `hui-generic-entity-row`, and that's great for most use-cases. But for some cases, it could be better to have more control over the layout.

**Comment by benct** [comment]
Should hopefully be fixed by home-assistant/frontend#8369.

Manual workaround with card-mod: `.info { flex: 1 1 30%; }`

**Comment by ivlis** [comment]
It has been broken since 2021.2 or 2021.1 AFAIR. This is annoying.

![image](https://user-images.githubusercontent.com/332942/114281567-055a7a00-9a0d-11eb-86f6-a07b19628d77.png)

**Comment by SAOPP** [comment]
Guys, I saw it again in lovelace, I remembered my problem, I decided to refresh my memory, as I understand it, now the problem still persists, right? And it is in the HA front?
