### ISSUE TITLE
Strange layout

### ISSUE THREAD

**Issue by jebeke65** [benct/lovelace-multiple-entity-row#194]
Running home assistant on my Synology Docker gives different layout than home assistant on my M1 Mac Docker.
Same files, different look and feel.

Any suggestions.

![Screenshot 2021-06-11 at 19 09 37](https://user-images.githubusercontent.com/47870698/121724852-c1592380-cae8-11eb-9cf7-df8990f8dd56.png)
![Screenshot 2021-06-11 at 19 07 33](https://user-images.githubusercontent.com/47870698/121724856-c28a5080-cae8-11eb-8256-1b39ae9535f0.png)
![Screenshot 2021-06-11 at 19 07 27](https://user-images.githubusercontent.com/47870698/121724857-c322e700-cae8-11eb-9721-80d81192fed2.png)

**Comment by tobi-bo** [comment]
I have this issue, too, but I have both "layouts" on the same HA installation and same client. From time to time I see a layout like the second picture, which is wrong. A reload with clear cache solves the issue for me. But it appears randomly again.

I see this behavior since the update to HA version 2021.6.4 (from 2021.5.5). Version of multiple-entity-row is 4.2.0.

**Comment by benct** [comment]
Strange.. Unfortunately, I have no idea how to fix it (if at all possible) as its random and I cannot reproduce the problem.

I'll have a look at the Lit update when I get the time.
