### ISSUE TITLE
Icon - entity state

### ISSUE THREAD

**Issue by majdzik84** [benct/lovelace-multiple-entity-row#25]
Is it possible to make the icon change (or change the color) as the entity state changes? (e.g. windows open / close)

**Comment by benct** [comment]
It's most likely possible! I'll have a look at how to implement that soon.

**Comment by ZioTitanok** [comment]
Is it possible to make the icon change as one of the entity state change (those listed in a row))?
Take the code below as example: can the icon change if switch1 or/and switch2 change state?

`
  - entity: switch.livingroom_tv
    type: custom:multiple-entity-row
    name: Multiple toggles
    name_state: main
    toggle: true
    primary:
      entity: switch.livingroom_light
      name: toggle1
      toggle: true
    secondary:
      entity: switch.livingroom_light_2
      name: toggle2
      toggle: true`

**Comment by jacekpaszkowski** [comment]
Or maybe it is just possible to display icon which set for entity object? For some entities i use icon_tamplate.

**Comment by jacekpaszkowski** [comment]
@benct so in v 3.0.0 it is possible to display entity icon instead of state?

**Comment by benct** [comment]
It's been possible to display icons for additional entities since v2.0.0. Version 3 made the icons change color based on entity state, as referenced by the topic of this issue.

The main entity object supports icon in the same way as other entity rows, and displays it to the left of the name. If you want the same icon instead of the state value, you could use `show_state: false` and add en additional entity object with `icon: true`?

**Comment by jacekpaszkowski** [comment]
Thanks, now i was able to get it work :)
