### ISSUE TITLE
"bug": latest update screwed    - state_color: true -

### ISSUE THREAD

**Issue by mbt45** [benct/lovelace-multiple-entity-row#45]
latest update linked  "state_color: true" of the first entity, to ALL the icons that follows at the same time, whether they are active or not.

**Comment by mbt45** [comment]
`entities:
  - entity: cover.tous_volets
    name: Tous Volets
    state_color: true
    entities:
    - icon: 'mdi:arrow-down'
      service: cover.close_cover
      service_data:
        entity_id: cover.tous_volets 
    - icon: 'mdi:stop'
      service: cover.stop_cover
      service_data:
        entity_id: cover.tous_volets
    - icon: 'mdi:arrow-up'
      service: cover.open_cover
      service_data:
        entity_id: cover.tous_volets`

**Comment by benct** [comment]
Well, not quite, but I understand this can be confusing.. You have one entity here (`cover.tous_volets`), which also acts as the state object for all the icons because they don't specify entity IDs themselves. So when the cover entity is active, the other icons are active too.

I should probably add a `state_color` option for each icon instead.. Meanwhile, I think you can "fix" this by adding 'entity: sensor.some_non_active_entity' to each icon config.

**Comment by mbt45** [comment]
I tried your suggestion. unfortunately it render the icon button unusable since it will now just popup the status of the 'sensor.some_non_active_entity'.
