### ISSUE TITLE
Feature Request: hide unavailable states (or at least make this an option)

### ISSUE THREAD

**Issue by ihaettypo** [benct/lovelace-multiple-entity-row#77]
The reason is for entities like such as yeelight, some states might not be available untill the light is turned on. I guess it's better to hide these states when they are unavailable.

**Comment by benct** [comment]
What should be displayed instead? It might look weird if the row is totally blank..

**Comment by ihaettypo** [comment]
> What should be displayed instead? It might look weird if the row is totally blank..

OK when I say states I actually mean attributes like brightness, color, etc., so when they are hidden the row would look just the same as a stock entity row (since the on/off state is always available unless the entity is offline)? 

And for the placeholder of unavailable states, maybe ask the user to choose from:

1. completely hidden (0 space occupied)
2. customized text/icon

by specifying in the configurations?

**Comment by ericvitale** [comment]
I was just about to request the same feature. Here are some examples...

Most of the time I don't adjust the brightness of my lights from the app, my automations do that. So I like to use this component because I don't need it to be an entity-slider-row. I would like to display the brightness_pct of the device next to the toggle. If the toggle is off, it currently displays "unavailable". I'd like it to just not be there unless it is available but still show the toggle.

Could you support {{ templates }} This way we could show attributes only if they are a certain value.

**Comment by xekil** [comment]
+1 for the fonctionnality

**Comment by xekil** [comment]
<a href="https://www.noelshack.com/2020-36-1-1598864671-suggest.jpg"><img src="https://image.noelshack.com/minis/2020/36/1/1598864671-suggest.png" border="0" alt="1598864671-suggest.jpg - envoi d'image avec NoelShack" title="1598864671-suggest.jpg"/></a>

**Comment by benct** [comment]
Additional entities should now be hidden if unavailable when setting `hide_unavailable: true` in version `3.5.0`.
